### PR TITLE
remove cssta, run more samples, add a more complex browser test

### PR DESCRIPTION
**Pull request by quantizor**
There are a couple bugs preventing me from finishing this at the moment:

~~https://github.com/tkh44/emotion/issues/274~~
~~https://github.com/styled-components/babel-plugin-styled-components/issues/81~~

### CODE REVIEW

**Comment by quantizor** [comment]
Latest results:

```
.-----------------------------------------------------------------------------------.
|                                      browser                                      |
|-----------------------------------------------------------------------------------|
|                                   |    styled     |    emotion    |   glamorous   |
|-----------------------------------|---------------|---------------|---------------|
| simple component                  | 0.067±0.023ms | 0.020±0.008ms | 0.078±0.037ms |
| prop changes                      | 0.177±0.099ms | 0.097±0.036ms | 0.200±0.128ms |
| prop shorthands                   | 0.078±0.056ms | 0.027±0.015ms | 0.096±0.081ms |
| prop shorthands with prop changes | 0.178±0.095ms | 0.151±0.013ms | 0.273±0.227ms |
| theming + dynamic styles          | 0.751±0.711ms | 0.519±0.278ms | 0.880±0.527ms |
'-----------------------------------------------------------------------------------'


.---------------------------------------------------.
|                      native                       |
|---------------------------------------------------|
|                                   |    styled     |
|-----------------------------------|---------------|
| simple component                  | 0.086±0.082ms |
| prop changes                      | 0.178±0.100ms |
| prop shorthands                   | 0.127±0.121ms |
| prop shorthands with prop changes | 0.271±0.159ms |
'---------------------------------------------------'
```

**Comment by quantizor** [comment]
Now with version numbers

```
.---------------------------------------------------------------------------------------------.
|                                           browser                                           |
|---------------------------------------------------------------------------------------------|
|                                   | styled (v2.2.1) | emotion (v7.3.2) | glamorous (v4.9.7) |
|-----------------------------------|-----------------|------------------|--------------------|
| simple component                  | 0.068±0.024ms   | 0.019±0.009ms    | 0.076±0.032ms      |
| prop changes                      | 0.169±0.071ms   | 0.103±0.044ms    | 0.174±0.069ms      |
| prop shorthands                   | 0.074±0.048ms   | 0.026±0.020ms    | 0.085±0.066ms      |
| prop shorthands with prop changes | 0.182±0.099ms   | 0.138±0.011ms    | 0.262±0.231ms      |
| theming + dynamic styles          | 0.644±0.419ms   | 0.487±0.334ms    | 0.807±0.666ms      |
'---------------------------------------------------------------------------------------------'
.-----------------------------------------------------.
|                       native                        |
|-----------------------------------------------------|
|                                   | styled (v2.2.1) |
|-----------------------------------|-----------------|
| simple component                  | 0.075±0.072ms   |
| prop changes                      | 0.181±0.169ms   |
| prop shorthands                   | 0.121±0.106ms   |
| prop shorthands with prop changes | 0.265±0.140ms   |
'-----------------------------------------------------'
```

**Comment by quantizor** [comment]
going to update emotion to v8 and then polish off this PR

**Comment by quantizor** [comment]
\+ emotion 8

```
.---------------------------------------------------------------------------------------------.
|                                           browser                                           |
|---------------------------------------------------------------------------------------------|
|                                   | styled (v2.2.1) | emotion (v8.0.5) | glamorous (v4.9.7) |
|-----------------------------------|-----------------|------------------|--------------------|
| simple component                  | 0.065±0.021ms   | 0.037±0.018ms    | 0.083±0.050ms      |
| prop changes                      | 0.172±0.092ms   | 0.074±0.038ms    | 0.194±0.092ms      |
| prop shorthands                   | 0.083±0.063ms   | 0.038±0.024ms    | 0.083±0.064ms      |
| prop shorthands with prop changes | 0.174±0.090ms   | 0.082±0.046ms    | 0.274±0.262ms      |
| theming + dynamic styles          | 0.589±0.292ms   | 0.365±0.296ms    | 0.839±0.766ms      |
'---------------------------------------------------------------------------------------------'
.-----------------------------------------------------.
|                       native                        |
|-----------------------------------------------------|
|                                   | styled (v2.2.1) |
|-----------------------------------|-----------------|
| simple component                  | 0.073±0.048ms   |
| prop changes                      | 0.185±0.145ms   |
| prop shorthands                   | 0.121±0.106ms   |
| prop shorthands with prop changes | 0.270±0.185ms   |
'-----------------------------------------------------'
```

**Comment by quantizor** [comment]
@mxstbr this is ready for review

**Review by mxstbr — APPROVED** [review]
Niiice, thank you @probablyup this is super helpful!

**Pull request merged**
