### PR TITLE
feat: add emotion + glamorous browser suites, styled-components preprocessing

### PR DESCRIPTION
**Pull request by quantizor**
initial run results:

```
Results for browser
                                   styled         cssta          emotion
---------------------------------  -------------  -------------  -------------
simple component                   0.469±0.131ms  0.031±0.007ms  0.089±0.016ms
prop changes                       0.767±0.145ms  0.084±0.004ms  0.397±0.065ms
prop shorthands                    0.307±0.064ms  0.019±0.005ms  0.080±0.019ms
prop shorthands with prop changes  0.669±0.047ms  0.078±0.021ms  0.471±0.035ms
```

### CODE REVIEW

**Comment by quantizor** [comment]
With styled-components preprocessing enabled:

```
Results for browser
                                   styled         cssta          emotion      
---------------------------------  -------------  -------------  -------------
simple component                   0.262±0.064ms  0.022±0.005ms  0.070±0.011ms
prop changes                       0.601±0.053ms  0.081±0.019ms  0.390±0.084ms
prop shorthands                    0.268±0.088ms  0.021±0.002ms  0.085±0.029ms
prop shorthands with prop changes  0.608±0.047ms  0.082±0.005ms  0.513±0.045ms
```

**Comment by quantizor** [comment]
With glamorous (react):

```
Results for browser
                                   styled         cssta          emotion        glamorous    
---------------------------------  -------------  -------------  -------------  -------------
simple component                   0.297±0.073ms  0.021±0.003ms  0.068±0.010ms  0.268±0.055ms
prop changes                       0.585±0.100ms  0.077±0.003ms  0.381±0.033ms  0.657±0.159ms
prop shorthands                    0.255±0.060ms  0.021±0.006ms  0.080±0.007ms  0.286±0.085ms
prop shorthands with prop changes  0.631±0.234ms  0.082±0.005ms  0.502±0.156ms  0.850±0.259ms
```

I tried to do `glamorous-native` and gave up because it has a rat's nest of dependencies that needs all sorts of gross babel stuff.

**Comment by quantizor** [comment]
That's it for this PR I think. @philpl @jacobp100

**Comment by mxstbr** [comment]
Wh000t this is fucking great, can't wait to land this!

**Comment by jacobp100** [comment]
This is great!

**Comment by kitten** [comment]
Beautiful :)

**Comment by kentcdodds** [comment]
Just as I suspected, they're all blazing fast.

**Comment by kitten** [comment]
@kentcdodds (this doesn't include the browser's css injection yet ^^ so it's just "raw" perf)

**Comment by kentcdodds** [comment]
Ah, good point.

I personally am not going to work on this (not to suggest you were asking me to). I appreciate a good benchmark as much as the next human, but I think it's clear that all of these solutions are fast enough. I think the glamorous community would benefit more from improved docs and supporting libraries than micro benchmarks to confirm that it's fast. This is why I'm not working on benchmarks.

That said, I think it's awesome if your community wants to work on that. Whatever brings people happiness 🤗

And thanks for taking the time to include glamorous! ❤️

**Comment by kitten** [comment]
@kentcdodds:

> I appreciate a good benchmark as much as the next human, but I think it's clear that all of these solutions are fast enough. [...]

AMEN! We'll probably also merge Glen's css injection perf fix, which will bring us up to speed quite literally. I don't expect anyone to work on benchmarks if they don't want to :smile: I myself are only benchmarking "in private" when I really need to.

Thanks for dropping by :heart:

**Comment by quantizor** [comment]
@philpl if you want to make a new ticket with suggestions for additional tests (like deep trees, use of theming, etc) I'd be happy to help out implementing them.

**Comment by tkh44** [comment]
@probablyup The only problem I have with this test and using `cssta` is that `cssta` does not accept string interpolations at all. If you are going to benchmark, you should be comparing similar strategies. You should either remove `cssta` from the benchmark or use inline styles for dynamic properties for all the tests. They will all be at the same speed if you were to do that. I think you should benchmark it as most people use it in that you should be using interpolated values.

**Comment by evan-scott-zocdoc** [comment]
No argument from me on `cssta`. @philpl?

Ugh always accidentally using my work account 😆

**Comment by mxstbr** [comment]
The benchmark isn't intended for sharing, it's intended for the `styled-components` developers to make sure we don't regress. The reason this repo even exists is because @jacobp100 (creator of `cssta`) made a benchmark for `cssta` which we then moved here 🤷‍♂️ 

That being said, I'm happy to remove `cssta` to make this sharable I guess.

**Comment by tkh44** [comment]
That's fine. I don't really care about the numbers I just wanted to make sure everyone was on the same page 😄 We have a similar situation and set up.

**Comment by jacobp100** [comment]
So there should definitely be benchmarks for string interpolations. These would obviously would be omitted for cssta, which goes down the css variables route instead.

I think it would be wrong to assume they will all perform the same if you use inline styles for dynamic properties. The first test is benchmarks how long it takes for the first render of a component, which is a very important metric.

I’d argue for benchmarking as many libraries as we can! I wasn’t aware of these libraries when I started this, but I would have included them!

**Comment by kitten** [comment]
I think it’s fine as long as we keep this in mind. We have no plans on publishing any results from these benchmarks and we should keep it this way :laughing: :wink:

**Pull request merged**
